'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.42000
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WindowsApp15.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _4494276_galaxy_wallpapers_hd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("4494276-galaxy-wallpapers-hd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property adds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("adds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BoutonPlus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BoutonPlus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BoutonPlusBlue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BoutonPlusBlue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BoutonPlusBlue1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BoutonPlusBlue1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BoutonPlusDarkViolet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BoutonPlusDarkViolet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BoutonPlusDarkViolet1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BoutonPlusDarkViolet1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BoutonPlusDeepPink() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BoutonPlusDeepPink", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BoutonPlusDeepPink1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BoutonPlusDeepPink1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BoutonPlusDodgerBlue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BoutonPlusDodgerBlue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BoutonPlusDodgerBlue1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BoutonPlusDodgerBlue1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BoutonPlusGreenYellow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BoutonPlusGreenYellow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BoutonPlusGreenYellow1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BoutonPlusGreenYellow1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BoutonPlusJaune() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BoutonPlusJaune", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BoutonPlusJaune1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BoutonPlusJaune1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BoutonPlusJaune2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BoutonPlusJaune2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BoutonPlusLightGreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BoutonPlusLightGreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BoutonPlusLightGreen1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BoutonPlusLightGreen1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BoutonPlusMediumSlateBlue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BoutonPlusMediumSlateBlue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BoutonPlusMediumSlateBlue1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BoutonPlusMediumSlateBlue1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BoutonPlusOrange() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BoutonPlusOrange", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BoutonPlusOrange1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BoutonPlusOrange1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BoutonPlusOrange2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BoutonPlusOrange2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BoutonPlusOrangeRouge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BoutonPlusOrangeRouge", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BoutonPlusOrangeRouge1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BoutonPlusOrangeRouge1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BoutonPlusRouge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BoutonPlusRouge", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BoutonPlusRouge1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BoutonPlusRouge1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BoutonPlusSpringGreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BoutonPlusSpringGreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BoutonPlusSpringGreen1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BoutonPlusSpringGreen1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BoutonPlusTurquoise() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BoutonPlusTurquoise", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BoutonPlusTurquoise1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BoutonPlusTurquoise1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property images() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sky_night_space_813269() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sky-night-space-813269", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
